Repository tensorflow/cloud, pull requests merged in 2020-08, with the labels that each got.

#151 Remove assumption that current directory of test is writable
  src/python/tensorflow_cloud/core/tests/unit/containerize_test.py
Labels: bug

#152 Refactor Optimizer client
  src/python/tensorflow_cloud/tuner/constants.py
  src/python/tensorflow_cloud/tuner/optimizer_client.py
Labels: enhancement

#160 Lint RELEASE.md
  RELEASE.md
Labels: cla: yes

#158 Propose added integration tests
  src/python/tensorflow_cloud/core/tests/integration/run_on_script_test.py
Labels: cla: yes

#163 Fix integration tests.
  src/python/tensorflow_cloud/core/tests/integration/run_on_script_test.py
Labels: cla: yes

#165 Remove requirements.txt from src/python
  src/python/requirements.txt
Labels: cla: yes

#166 Add user agent tracking for Cloud Build service call.
  src/python/tensorflow_cloud/core/containerize.py
  src/python/tensorflow_cloud/core/tests/unit/containerize_test.py
Labels: cla: yes
